title: Serenityd Blog
subtitle:
description: 诗万卷，酒千觞，几曾着眼看侯王
author: Serenityd
language: zh-Hans
timezone:

theme: next
menu_icons:
  enable: true
  home: /
  archives: /archives
  tags: /tags

sidebar:
  position: left
  display: post
avatar: /images/avatar.jpg
widgets:
- search
- category
- recent_posts
- tag
- tagcloud
post_asset_folder: true 
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
deploy:
  type: git
  repository: git@github.com:serenityd/serenityd.github.io.git
  branch: master
